### ISSUE TITLE
[EPIC]: UVOL2

### ISSUE THREAD

**Issue by CITIZENDOT** [XRFoundation/UniversalVolumetric#186]
### UVOL2 at a high-level

- **.uvol.manifest.json**  - contains structured information about framerate, audio & video texture sources (ktx2 vs mp4), geometry buffer ranges, etc, compatible with gltf conventions
- **.uvol.mp4** - video for texture (and audio) 
- **.uvol.ktx2.bin** - binary buffer of compresses ktx2 texture data sequence
- **.uvol.drc.bin**  - binary buffer of compressed drc sequence 
- **.uvol.gltf/glb** - gltf w/ uvol extensions (pointing to uvol manifest and compressed geometry buffer)
- **.uvol.usd/usda/usdc/usdz** - usd w/ uvol extensions  (pointing to uvol manifest and compressed geometry buffer)
- **.uvol / .uvol.crt.bin** - DEPRECATED (UVOL1 format) binary buffer of compressed corto sequence
- **.manifest.json** - DEPRECATED (UVOL1 format) - replaced with `.uvol.manifest.json` above

- [ ] https://github.com/EtherealEngine/Universal-Volumetric/issues/182
- [ ] https://github.com/EtherealEngine/Universal-Volumetric/issues/184
- [ ] https://github.com/EtherealEngine/Universal-Volumetric/issues/183
- [ ] https://github.com/EtherealEngine/Universal-Volumetric/issues/185
